# filepath: /c:/www/symfony/symfony_marketplace/.github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql

      - name: Instalar dependências do Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Build frontend (opcional)
        run: |
          if [ -f package.json ]; then
            npm install && npm run build
          fi

      - name: Deploy para HostGator
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          rsync -avz --delete --exclude '.git' --exclude 'node_modules' --exclude 'vendor' ./ user@hostgator:/path/to/your/project
          ssh user@hostgator 'cd /path/to/your/project && composer install --no-dev --optimize-autoloader'
          ssh user@hostgator 'cd /path/to/your/project && php bin/console cache:clear --env=prod'