# filepath: /c:/www/symfony/symfony_marketplace/.github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql
  deploy-desenvolvimento:
    runs-on: ubuntu-latest
    environment: 
      name: desenvolvimento
      url: https://marketplace.fredtamashiro.com.br
    needs: build
    steps:
      - name: Hostgator Deploy
        uses: easingthemes/SSH_PRIVATE_KEY-Deploy@v2
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_PORT: 2222
          REMOTE_USER: ${{ secrets.USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "/"
          TARGET: "/public_html/marketplace"
          EXCLUDE: ".git*"
